export const SENTENCES = [
  "He found the end of the rainbow and was surprised at what was there",
  "Flesh colored yoga pants were far worse than even he feared",
  "He was disappointed when he found the beach to be so sandy",
  "The delicious aroma from the kitchen was ruined by cigarette smoke",
  "Its always a good idea to seek shelter from the evil gaze of the sun",
  "Behind the window was a reflection that only instilled fear",
  "The roads were impassable due to the snow",
  "There were a lot of paintings of monkeys waving bamboo sticks in the gallery",
  "I love eating toasted cheese and tuna sandwiches",
  "People generally approve of dogs eating cat food but not cats eating dog food",
  "Nothing seemed out of place except the washing machine in the bar",
  "The worst thing about being at the top of the career ladder is that theres a long way to fall",
  "He looked behind the door and didnt like what he saw",
  "The government felt confident that nobody would ever suspect the spy pigeon",
  "She looked at the masterpiece hanging in the museum and thought that her toddler could do better",
  "They say people remember important moments in their life well yet no one remembers their own birth",
  "I became paranoid that the school of jellyfish was going to sting me",
  "He creeped like a lion stalking a gazelle on the savannah",
  "She accidentally created a whole new universe",
  "There is a reason that roses have thorns",
  "Some clothes just should not be worn by some people",
  "Everyone pretends to like wheat until you mention barley",
  "The beauty of the sunset was obscured by the industrial cranes",
  "When I was little I had a car door slammed shut on my hand and I still remember it vividly",
  "The green tea and avocado smoothie turned out exactly as expected",
  "Iguanas were falling out of the trees",
  "The body piercing didnt go exactly as he expected",
  "When money was tight he would get his lunch money from the local wishing well",
  "The opportunity of a lifetime passed before him as he tried to decide between a cone or a cup",
  "Choosing to do nothing is still a choice after all",
  "She insisted that cleaning out her closet was the key to good living",
  "This is simply not the time and place to do it",
  "He decided to fake his disappearance to avoid jail",
  "The shooter says goodbye to his nemesis",
  "There are few things better in life than a slice of pie",
  "Today I heard something new and unmemorable",
  "Everyone says they love nature until they realize how dangerous she can be",
  "I really want to go to work but I am too sick to drive",
  "There are no heroes in a punk rock band",
  "They desperately needed another drummer since the current one only knew how to play bongos",
  "The efficiency we have at removing trash has made creating trash more acceptable",
  "I trust everything thats written in purple ink",
  "The sun had set and so had his dreams",
  "The light that burns twice as bright burns half as long",
  "She was the type of girl who wanted to live in a pink house",
  "You will see the rainbow bridge after it rains cats and dogs",
  "He liked driving around town with his hazard lights on",
  "He felt that dining on the bridge brought romance to this relationship",
  "The sign said there was road work ahead so he decided to slow down",
  "Who could be calling on the phone this late at night",
  "Her brother broke his arm while playing hockey",
  "He made a list of all the places he wants to visit",
  "The bully at school was mean to everyone except me",
  "The earthquake was the biggest one that we had ever experienced",
  "Blue candies are more tasty than orange candies",
  "There is no need to make a big deal out of it",
  "The big ugly tree destroys the beauty of the house",
  "He went to the animal shelter and got four cats",
  "The coordinated professionals completed their difficult tasks successfully",
  "The lack of budget saw the projects failure",
  "We spent a lot of time looking for a parking space",
  "Democracy is a form of government in which the people vote for change but get more of the same",
  "I was the owner of the only swimming pool in the city that had a diving board",
  "Children often want to do things that are dangerous without knowing better",
  "He was well respected for his management skills",
  "He reached for the bottle and poured himself another drink",
  "My father helped me out of my financial difficulties",
  "We queued up to get tickets for the concert",
  "I have only seen my old classmate twice since we left school",
  "Their planet was cooling down internally and would become uninhabitable in five hundred years",
  "The bystander pulled out his phone and took a picture of the wrecked car",
  "We are still several miles away from the city",
  "My boss said it would be alright if I didnt attend this afternoons meeting",
  "The best thing would be for you to do the work yourself",
  "The kid is very interested in chess but he does not know how to play",
  "The worst kind of hangover is emotional hangover",
  "He said he left early because had an important call to make",
  "That man is richest whose pleasures are the cheapest",
  "During First Contact humanity did not know what to expect of the alien race",
  "I dont care what you do when youre not at work as long as the work gets done",
  "We were in the hallway of the second floor of the hospital",
  "The frivolous activity turned wrathful after someone voiced their opinion",
  "They paused to admire the silent landscape of the night",
  "Never do that again or I will stop being your friend",
  "I want to talk about the benefits of having a pet pig",
  "Seek success but always be prepared for failure",
  "My seemingly nice neighbor had skeletons in his closet",
  "He was an introvert that extroverts seemed to love",
  "When confronted with a rotary dial phone the teenager was perplexed",
  "They say that dogs are mans best friend but this cat was setting out to sabotage that theory",
  "The boy didnt understand why his parents wont let him sell his little sister at the garage sale",
  "In hopes of finding out the truth he entered the library",
  "She was too busy always talking about what she wanted to do to actually do any of it",
  "There arent enough towels in the world to stop the sewage flowing from his mouth",
  "According to the map the mountains are to the west",
  "He is the type of guy who wears sunglasses at night",
  "The fisherman hoped to catch dinner from the shallow river",
  "The tour bus was packed with teenage girls heading toward their next adventure",
  "My bandaid was no longer sticky and it fell off while I was exercising",
  "You should go to the beach for your next vacation"
]
